"""Seed AI quests with templates and labels

Revision ID: 0017_seed_ai_quests
Revises: 0016_poi_required_ai_metadata
Create Date: 2026-05-06 00:00:00.000000
"""

from datetime import datetime
from uuid import uuid4

from alembic import op
import sqlalchemy as sa

revision = "0017_seed_ai_quests"
down_revision = "0016_poi_required_ai_metadata"
branch_labels = None
depends_on = None


def upgrade() -> None:
    now = datetime.utcnow()
    rows = [
        {
            "id": uuid4(),
            "title": "Coffee hunt",
            "description": "Find coffee",
            "xp_reward": 60,
            "difficulty": "easy",
            "approval_rate": 1.0,
            "time_limit_hours": None,
            "location_required": False,
            "is_active": True,
            "template": "Take a photo of a {label}",
            "labels": ["coffee", "cafe", "drink"],
            "label_rules": {"coffee": 0.6},
            "min_confidence": 0.5,
            "poi_required": False,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "title": "Street view",
            "description": "Find a street",
            "xp_reward": 50,
            "difficulty": "easy",
            "approval_rate": 1.0,
            "time_limit_hours": None,
            "location_required": False,
            "is_active": True,
            "template": "Spot a {label} nearby",
            "labels": ["street", "road"],
            "label_rules": {"street": 0.5},
            "min_confidence": 0.5,
            "poi_required": False,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "title": "Park moment",
            "description": "Find a park",
            "xp_reward": 70,
            "difficulty": "medium",
            "approval_rate": 1.0,
            "time_limit_hours": None,
            "location_required": False,
            "is_active": True,
            "template": "Find a {label} and capture it",
            "labels": ["park", "tree", "grass"],
            "label_rules": {"park": 0.55},
            "min_confidence": 0.5,
            "poi_required": True,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "title": "Bridge view",
            "description": "Find a bridge",
            "xp_reward": 80,
            "difficulty": "medium",
            "approval_rate": 1.0,
            "time_limit_hours": None,
            "location_required": False,
            "is_active": True,
            "template": "Take a shot of a {label}",
            "labels": ["bridge"],
            "label_rules": {"bridge": 0.6},
            "min_confidence": 0.5,
            "poi_required": False,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "title": "Market visit",
            "description": "Find a market",
            "xp_reward": 70,
            "difficulty": "medium",
            "approval_rate": 1.0,
            "time_limit_hours": None,
            "location_required": False,
            "is_active": True,
            "template": "Look for a {label} and take a picture",
            "labels": ["market", "store"],
            "label_rules": {"market": 0.55},
            "min_confidence": 0.5,
            "poi_required": False,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "title": "Food stop",
            "description": "Find food",
            "xp_reward": 60,
            "difficulty": "easy",
            "approval_rate": 1.0,
            "time_limit_hours": None,
            "location_required": False,
            "is_active": True,
            "template": "Catch a {label} on camera",
            "labels": ["food", "meal", "dish"],
            "label_rules": {"food": 0.55},
            "min_confidence": 0.5,
            "poi_required": False,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "title": "Restaurant hunt",
            "description": "Find a restaurant",
            "xp_reward": 70,
            "difficulty": "medium",
            "approval_rate": 1.0,
            "time_limit_hours": None,
            "location_required": False,
            "is_active": True,
            "template": "Take a photo of a {label}",
            "labels": ["restaurant"],
            "label_rules": {"restaurant": 0.6},
            "min_confidence": 0.5,
            "poi_required": True,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "title": "Drink moment",
            "description": "Find a drink",
            "xp_reward": 50,
            "difficulty": "easy",
            "approval_rate": 1.0,
            "time_limit_hours": None,
            "location_required": False,
            "is_active": True,
            "template": "Spot a {label} in real life",
            "labels": ["drink", "beverage"],
            "label_rules": {"drink": 0.5},
            "min_confidence": 0.5,
            "poi_required": False,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "title": "Building shot",
            "description": "Find a building",
            "xp_reward": 60,
            "difficulty": "easy",
            "approval_rate": 1.0,
            "time_limit_hours": None,
            "location_required": False,
            "is_active": True,
            "template": "Take a shot of a {label}",
            "labels": ["building", "architecture"],
            "label_rules": {"building": 0.5},
            "min_confidence": 0.5,
            "poi_required": False,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid4(),
            "title": "River view",
            "description": "Find a river",
            "xp_reward": 60,
            "difficulty": "easy",
            "approval_rate": 1.0,
            "time_limit_hours": None,
            "location_required": False,
            "is_active": True,
            "template": "Find a {label} and capture it",
            "labels": ["river", "water"],
            "label_rules": {"river": 0.5},
            "min_confidence": 0.5,
            "poi_required": False,
            "created_at": now,
            "updated_at": now,
        },
    ]

    op.bulk_insert(
        sa.table(
            "quests",
            sa.column("id"),
            sa.column("title"),
            sa.column("description"),
            sa.column("xp_reward"),
            sa.column("difficulty"),
            sa.column("approval_rate"),
            sa.column("time_limit_hours"),
            sa.column("location_required"),
            sa.column("is_active"),
            sa.column("template"),
            sa.column("labels", sa.JSON()),
            sa.column("label_rules", sa.JSON()),
            sa.column("min_confidence"),
            sa.column("poi_required"),
            sa.column("created_at"),
            sa.column("updated_at"),
        ),
        rows,
    )


def downgrade() -> None:
    op.execute("DELETE FROM quests WHERE template IS NOT NULL AND labels IS NOT NULL")
