"""Seed AI quests with templates and labels

Revision ID: 0017_seed_ai_quests
Revises: 0016_poi_required_ai_metadata
Create Date: 2026-05-06 00:00:00.000000
"""

from datetime import datetime
from uuid import UUID

from alembic import op
import sqlalchemy as sa

revision = "0017_seed_ai_quests"
down_revision = "0016_poi_required_ai_metadata"
branch_labels = None
depends_on = None


def upgrade() -> None:
    now = datetime.utcnow()
    rows = [
        {
            "id": UUID("1ad18312-8d6b-4aff-91dd-d0cc799f1136"),
            "title": "Building shot",
            "description": "Find a building",
            "xp_reward": 60,
            "difficulty": "easy",
            "approval_rate": 1.0,
            "time_limit_hours": None,
            "location_required": False,
            "is_active": True,
            "template": "Take a shot of a {label}",
            "labels": ["building", "architecture"],
            "label_rules": {"building": 0.5},
            "min_confidence": 0.5,
            "poi_required": False,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": UUID("248752f9-d237-46a9-9d38-757afdf418c7"),
            "title": "Market visit",
            "description": "Find a market",
            "xp_reward": 70,
            "difficulty": "medium",
            "approval_rate": 1.0,
            "time_limit_hours": None,
            "location_required": False,
            "is_active": True,
            "template": "Look for a {label} and take a picture",
            "labels": ["market", "store"],
            "label_rules": {"market": 0.55},
            "min_confidence": 0.5,
            "poi_required": False,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": UUID("26bf5917-413d-4456-8b60-3da04fa264d4"),
            "title": "Pen shot",
            "description": "Take a photo of a pen or writing tool.",
            "xp_reward": 35,
            "difficulty": "easy",
            "approval_rate": 1.0,
            "time_limit_hours": None,
            "location_required": False,
            "is_active": True,
            "template": "Take a photo of a {label}",
            "labels": ["pen", "pencil"],
            "label_rules": {"pen": 0.5, "pencil": 0.5},
            "min_confidence": 0.5,
            "poi_required": False,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": UUID("362b5353-41f4-463f-9b6d-11d131950ead"),
            "title": "Laptop shot",
            "description": "Take a photo of a laptop or portable computer.",
            "xp_reward": 45,
            "difficulty": "easy",
            "approval_rate": 1.0,
            "time_limit_hours": None,
            "location_required": False,
            "is_active": True,
            "template": "Take a photo of a {label}",
            "labels": ["laptop", "computer", "personal computer"],
            "label_rules": {"laptop": 0.55, "computer": 0.6, "personal computer": 0.55},
            "min_confidence": 0.5,
            "poi_required": False,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": UUID("39f6628f-6e3d-4cd0-a663-c6ad3e61b979"),
            "title": "Table shot",
            "description": "Capture a table clearly in the frame.",
            "xp_reward": 40,
            "difficulty": "easy",
            "approval_rate": 1.0,
            "time_limit_hours": None,
            "location_required": False,
            "is_active": True,
            "template": "Take a photo of a {label}",
            "labels": ["table", "desk"],
            "label_rules": {"table": 0.55, "desk": 0.55},
            "min_confidence": 0.5,
            "poi_required": False,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": UUID("5b33e386-726f-4b02-8d32-1d96edfc5cf9"),
            "title": "Bag shot",
            "description": "Take a photo of a bag, handbag, or backpack.",
            "xp_reward": 40,
            "difficulty": "easy",
            "approval_rate": 1.0,
            "time_limit_hours": None,
            "location_required": False,
            "is_active": True,
            "template": "Take a photo of a {label}",
            "labels": ["bag", "backpack", "handbag"],
            "label_rules": {"bag": 0.5, "backpack": 0.5, "handbag": 0.5},
            "min_confidence": 0.5,
            "poi_required": False,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": UUID("727da918-a20b-473a-b524-3bc0d7a46943"),
            "title": "Bridge view",
            "description": "Find a bridge",
            "xp_reward": 80,
            "difficulty": "medium",
            "approval_rate": 1.0,
            "time_limit_hours": None,
            "location_required": False,
            "is_active": True,
            "template": "Take a shot of a {label}",
            "labels": ["bridge"],
            "label_rules": {"bridge": 0.6},
            "min_confidence": 0.5,
            "poi_required": False,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": UUID("8b80cd27-e00d-47fa-8b81-1f7f063145f7"),
            "title": "Restaurant hunt",
            "description": "Find a restaurant",
            "xp_reward": 70,
            "difficulty": "medium",
            "approval_rate": 1.0,
            "time_limit_hours": None,
            "location_required": False,
            "is_active": True,
            "template": "Take a photo of a {label}",
            "labels": ["restaurant"],
            "label_rules": {"restaurant": 0.6},
            "min_confidence": 0.5,
            "poi_required": False,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": UUID("933e853e-0111-40c7-ac46-a71abbd33287"),
            "title": "Coffee hunt",
            "description": "Find coffee",
            "xp_reward": 60,
            "difficulty": "easy",
            "approval_rate": 1.0,
            "time_limit_hours": None,
            "location_required": False,
            "is_active": True,
            "template": "Take a photo of a {label}",
            "labels": ["cafe", "beverage", "mug", "tableware", "drink", "coffee", "cup"],
            "label_rules": {
                "Drinkware": 0.6,
                "Tableware": 0.6,
                "Cup": 0.6,
                "Mug": 0.6,
                "Drink": 0.6,
            },
            "min_confidence": 0.5,
            "poi_required": False,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": UUID("96fe0c18-7136-4a36-b6e1-a64710e77532"),
            "title": "Chair shot",
            "description": "Capture a chair clearly in the frame.",
            "xp_reward": 40,
            "difficulty": "easy",
            "approval_rate": 1.0,
            "time_limit_hours": None,
            "location_required": False,
            "is_active": True,
            "template": "Take a photo of a {label}",
            "labels": ["chair"],
            "label_rules": {"chair": 0.55},
            "min_confidence": 0.5,
            "poi_required": False,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": UUID("9e5993fb-2f27-4d8d-bcfe-d06da268b449"),
            "title": "River view",
            "description": "Find a river",
            "xp_reward": 60,
            "difficulty": "easy",
            "approval_rate": 1.0,
            "time_limit_hours": None,
            "location_required": False,
            "is_active": True,
            "template": "Find a {label} and capture it",
            "labels": ["river", "water"],
            "label_rules": {"river": 0.5},
            "min_confidence": 0.5,
            "poi_required": False,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": UUID("a65f6494-33a0-413b-9f67-c89306f2b08d"),
            "title": "People shot",
            "description": "Take a photo with at least one person clearly visible.",
            "xp_reward": 55,
            "difficulty": "easy",
            "approval_rate": 1.0,
            "time_limit_hours": None,
            "location_required": False,
            "is_active": True,
            "template": "Capture a {label} in the frame",
            "labels": ["person", "people", "human"],
            "label_rules": {"person": 0.55, "people": 0.55, "human": 0.55},
            "min_confidence": 0.5,
            "poi_required": False,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": UUID("b99eb8ce-8b14-4cb8-81d5-b5d71e3ac8df"),
            "title": "Drinkware shot",
            "description": "Take a photo of a cup, water bottle, or drink.",
            "xp_reward": 40,
            "difficulty": "easy",
            "approval_rate": 1.0,
            "time_limit_hours": None,
            "location_required": False,
            "is_active": True,
            "template": "Take a photo of a {label}",
            "labels": ["drinkware", "cup", "water bottle", "drink", "beverage"],
            "label_rules": {"drinkware": 0.5, "cup": 0.5, "water bottle": 0.5, "drink": 0.5},
            "min_confidence": 0.5,
            "poi_required": False,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": UUID("c6ed305f-387b-40a9-89b3-3dbb25ccc7ec"),
            "title": "Street view",
            "description": "Find a street",
            "xp_reward": 50,
            "difficulty": "easy",
            "approval_rate": 1.0,
            "time_limit_hours": None,
            "location_required": False,
            "is_active": True,
            "template": "Spot a {label} nearby",
            "labels": ["street", "road"],
            "label_rules": {"street": 0.5},
            "min_confidence": 0.5,
            "poi_required": False,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": UUID("d5a5923a-942a-43ec-90e1-859bda8833c0"),
            "title": "Dog shot",
            "description": "Take a photo with a dog clearly visible.",
            "xp_reward": 55,
            "difficulty": "easy",
            "approval_rate": 1.0,
            "time_limit_hours": None,
            "location_required": False,
            "is_active": True,
            "template": "Capture a {label} in the frame",
            "labels": ["dog"],
            "label_rules": {"dog": 0.55},
            "min_confidence": 0.5,
            "poi_required": False,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": UUID("d768a33e-6b13-40b9-9b4b-8f0d06aeb28c"),
            "title": "Drink moment",
            "description": "Find a drink",
            "xp_reward": 50,
            "difficulty": "easy",
            "approval_rate": 1.0,
            "time_limit_hours": None,
            "location_required": False,
            "is_active": True,
            "template": "Spot a {label} in real life",
            "labels": ["drink", "beverage"],
            "label_rules": {"Drinkware": 0.5},
            "min_confidence": 0.5,
            "poi_required": False,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": UUID("d9bfde7a-fd9f-4562-b64b-3f7b4bec7fd5"),
            "title": "Cat shot",
            "description": "Take a photo with a cat clearly visible.",
            "xp_reward": 55,
            "difficulty": "easy",
            "approval_rate": 1.0,
            "time_limit_hours": None,
            "location_required": False,
            "is_active": True,
            "template": "Capture a {label} in the frame",
            "labels": ["cat"],
            "label_rules": {"cat": 0.55},
            "min_confidence": 0.5,
            "poi_required": False,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": UUID("e265e459-202d-401d-8f35-f444090a060d"),
            "title": "Park moment",
            "description": "Find a park",
            "xp_reward": 70,
            "difficulty": "medium",
            "approval_rate": 1.0,
            "time_limit_hours": None,
            "location_required": False,
            "is_active": True,
            "template": "Find a {label} and capture it",
            "labels": ["park", "tree", "grass"],
            "label_rules": {"park": 0.55},
            "min_confidence": 0.5,
            "poi_required": False,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": UUID("e8abf7a5-1913-4a0d-8ffb-3c193c1a999d"),
            "title": "Food stop",
            "description": "Find food",
            "xp_reward": 60,
            "difficulty": "easy",
            "approval_rate": 1.0,
            "time_limit_hours": None,
            "location_required": False,
            "is_active": True,
            "template": "Catch a {label} on camera",
            "labels": ["food", "meal", "dish"],
            "label_rules": {"food": 0.55},
            "min_confidence": 0.5,
            "poi_required": False,
            "created_at": now,
            "updated_at": now,
        },
    ]

    op.bulk_insert(
        sa.table(
            "quests",
            sa.column("id"),
            sa.column("title"),
            sa.column("description"),
            sa.column("xp_reward"),
            sa.column("difficulty"),
            sa.column("approval_rate"),
            sa.column("time_limit_hours"),
            sa.column("location_required"),
            sa.column("is_active"),
            sa.column("template"),
            sa.column("labels", sa.JSON()),
            sa.column("label_rules", sa.JSON()),
            sa.column("min_confidence"),
            sa.column("poi_required"),
            sa.column("created_at"),
            sa.column("updated_at"),
        ),
        rows,
    )


def downgrade() -> None:
    op.execute("DELETE FROM quests WHERE template IS NOT NULL AND labels IS NOT NULL")
