"""add location_name to posts

Revision ID: 34bb1bc2e504
Revises: 0028_drop_unused_reco_tables
Create Date: 2026-05-17 16:12:39.801484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '34bb1bc2e504'
down_revision = '0028_drop_unused_reco_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_detection_logs_submission'), table_name='ai_detection_logs')
    op.create_index(op.f('ix_ai_detection_logs_submission_id'), 'ai_detection_logs', ['submission_id'], unique=False)
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('follows', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_follows_follower_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_following_id'), table_name='follows')
    op.alter_column('likes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_likes_post_id'), table_name='likes')
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_notifications_user_created'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_unread'), table_name='notifications')
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_index(op.f('ix_pois_lat_lng'), table_name='pois')
    op.add_column('posts', sa.Column('location_name', sa.Text(), nullable=True))
    op.alter_column('posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_user_created'), table_name='posts')
    op.alter_column('quests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('quests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_quests_poi_id'), table_name='quests')
    op.drop_index(op.f('ix_reco_logs_event'), table_name='recommendation_logs')
    op.drop_index(op.f('ix_reco_logs_quest'), table_name='recommendation_logs')
    op.drop_index(op.f('ix_reco_logs_request'), table_name='recommendation_logs')
    op.drop_index(op.f('ix_reco_logs_user_created'), table_name='recommendation_logs')
    op.create_index(op.f('ix_recommendation_logs_event'), 'recommendation_logs', ['event'], unique=False)
    op.create_index(op.f('ix_recommendation_logs_quest_id'), 'recommendation_logs', ['quest_id'], unique=False)
    op.create_index(op.f('ix_recommendation_logs_request_id'), 'recommendation_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_recommendation_logs_user_id'), 'recommendation_logs', ['user_id'], unique=False)
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('refresh_tokens_token_hash_key'), 'refresh_tokens', type_='unique')
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.alter_column('submissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_submissions_poi_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_status_created'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_suspicious'), table_name='submissions')
    op.create_index(op.f('ix_submissions_is_suspicious'), 'submissions', ['is_suspicious'], unique=False)
    op.alter_column('user_badges', 'earned_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_user_badges_user_badge'), 'user_badges', type_='unique')
    op.drop_index(op.f('ix_user_quest_stats_user'), table_name='user_quest_stats')
    op.drop_constraint(op.f('uq_user_quest_stats_user_category'), 'user_quest_stats', type_='unique')
    op.create_index(op.f('ix_user_quest_stats_category_id'), 'user_quest_stats', ['category_id'], unique=False)
    op.create_index(op.f('ix_user_quest_stats_user_id'), 'user_quest_stats', ['user_id'], unique=False)
    op.alter_column('user_quests', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_quests', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_user_quests_user_status'), table_name='user_quests')
    op.drop_constraint(op.f('uq_user_quests_user_quest'), 'user_quests', type_='unique')
    op.alter_column('users', 'level_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.alter_column('xp_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_xp_transactions_submission'), 'xp_transactions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_xp_transactions_submission'), 'xp_transactions', ['submission_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('xp_transactions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'level_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(op.f('uq_user_quests_user_quest'), 'user_quests', ['user_id', 'quest_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_user_quests_user_status'), 'user_quests', ['user_id', 'status'], unique=False)
    op.alter_column('user_quests', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('user_quests', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_user_quest_stats_user_id'), table_name='user_quest_stats')
    op.drop_index(op.f('ix_user_quest_stats_category_id'), table_name='user_quest_stats')
    op.create_unique_constraint(op.f('uq_user_quest_stats_user_category'), 'user_quest_stats', ['user_id', 'category_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_user_quest_stats_user'), 'user_quest_stats', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_user_badges_user_badge'), 'user_badges', ['user_id', 'badge_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_badges', 'earned_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_submissions_is_suspicious'), table_name='submissions')
    op.create_index(op.f('ix_submissions_suspicious'), 'submissions', ['is_suspicious'], unique=False)
    op.create_index(op.f('ix_submissions_status_created'), 'submissions', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_submissions_poi_id'), 'submissions', ['poi_id'], unique=False)
    op.alter_column('submissions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.create_unique_constraint(op.f('refresh_tokens_token_hash_key'), 'refresh_tokens', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_recommendation_logs_user_id'), table_name='recommendation_logs')
    op.drop_index(op.f('ix_recommendation_logs_request_id'), table_name='recommendation_logs')
    op.drop_index(op.f('ix_recommendation_logs_quest_id'), table_name='recommendation_logs')
    op.drop_index(op.f('ix_recommendation_logs_event'), table_name='recommendation_logs')
    op.create_index(op.f('ix_reco_logs_user_created'), 'recommendation_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_reco_logs_request'), 'recommendation_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_reco_logs_quest'), 'recommendation_logs', ['quest_id'], unique=False)
    op.create_index(op.f('ix_reco_logs_event'), 'recommendation_logs', ['event'], unique=False)
    op.create_index(op.f('ix_quests_poi_id'), 'quests', ['poi_id'], unique=False)
    op.alter_column('quests', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('quests', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_posts_user_created'), 'posts', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    op.alter_column('posts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('posts', 'location_name')
    op.create_index(op.f('ix_pois_lat_lng'), 'pois', ['latitude', 'longitude'], unique=False)
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.create_index(op.f('ix_notifications_user_unread'), 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_created'), 'notifications', ['user_id', 'created_at'], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_likes_post_id'), 'likes', ['post_id'], unique=False)
    op.alter_column('likes', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_follows_following_id'), 'follows', ['following_id'], unique=False)
    op.create_index(op.f('ix_follows_follower_id'), 'follows', ['follower_id'], unique=False)
    op.alter_column('follows', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('comments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.drop_index(op.f('ix_ai_detection_logs_submission_id'), table_name='ai_detection_logs')
    op.create_index(op.f('ix_ai_detection_logs_submission'), 'ai_detection_logs', ['submission_id'], unique=False)
    # ### end Alembic commands ###
