"""Add consolation_xp

Revision ID: f0819b0d0db7
Revises: 34bb1bc2e504
Create Date: 2026-05-17 16:59:10.072177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0819b0d0db7'
down_revision = '34bb1bc2e504'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_quests', sa.Column('consolation_xp', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_quests', 'consolation_xp')
    # ### end Alembic commands ###
