"""Add CONSOLATION to XpSource

Revision ID: f91a395ba849
Revises: f0819b0d0db7
Create Date: 2026-05-17 17:01:58.032351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f91a395ba849'
down_revision = 'f0819b0d0db7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE xp_source_enum ADD VALUE 'consolation'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
