"""Add post visibility

Revision ID: fd3149538e98
Revises: 0053_add_quest_image_url
Create Date: 2026-06-15 21:56:17.365217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd3149538e98'
down_revision = '0053_add_quest_image_url'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create enum type first (Alembic sometimes requires this for Enums)
    post_visibility_enum = sa.Enum('public', 'friends', 'private', name='post_visibility_enum')
    post_visibility_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('posts', sa.Column('visibility', post_visibility_enum, server_default='public', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'visibility')
    
    post_visibility_enum = sa.Enum('public', 'friends', 'private', name='post_visibility_enum')
    post_visibility_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
